server_port: 8765
entity_id: "https://edugain.fedservice.lh"
signing_key_file: "/data/signing.key"
organization_name: "eduGAIN"
data_location: "/data/data"
human_readable_storage: true
metadata_policy_file: "/data/metadata-policy.json"
endpoints:
  fetch:
    path: "/fetch"
  list:
    path: "/list"
  resolve:
    path: "/resolve"
  trust_mark:
    path: "/trustmark"
  trust_mark_status:
    path: "/trustmark/status"
  trust_mark_list:
    path: "/trustmark/list"
trust_mark_specs:
  - trust_mark_type: "https://edugain.org/member"
    lifetime: 7200
    logo_uri: "https://edugain.org/wp-content/uploads/2018/02/eduGAIN.jpg"
    checker:
      type: trust_path
      config:
        trust_anchors:
          - entity_id: "https://surfconext.fedservice.lh"
          - entity_id: "https://garr.fedservice.lh"
          - entity_id: "https://incommon.fedservice.lh"
          - entity_id: "https://haka.fedservice.lh"
          - entity_id: "https://sunet.fedservice.lh"
trust_mark_issuers:
  https://edugain.org/member:
    - "https://edugain.fedservice.lh"
  https://erasmus-plus.ec.europa.eu:
    - "https://erasmus-plus.fedservice.lh"
  "http://www.csc.fi/haka/member":
    - "https://haka.fedservice.lh"
  "https://puhuri.io":
    - "https://puhuri.fedservice.lh"
  https://incommon.org/federation/member:
    - "https://incommon.fedservice.lh"
trust_mark_owners:
  "https://refeds.org/sirtfi":
    entity_id: "https://refeds.fedservice.lh"
    jwks: %REFEDS_JWKS%
trust_marks:
  - trust_mark_type: "https://edugain.org/member"
    trust_mark_issuer: "https://edugain.fedservice.lh"
